try in bash

diff --git a/.github/workflows/unit_tests.yml b/.github/workflows/unit_tests.yml
--- a/.github/workflows/unit_tests.yml
+++ b/.github/workflows/unit_tests.yml
@@ -23,16 +23,14 @@ jobs:
         auto-activate-base: false
 
     - name: Install hierarchSIR 
+      shell: bash -l {0}
       run: |
-        conda init bash
-        source ~/.bashrc
-        conda activate hierarchSIR
+        conda activate hierarchSIR || (echo "Environment not found, creating..." && conda env create -f hierarchSIR_env.yml && conda activate hierarchSIR)
         python -m pip install --upgrade pip
         pip install -e . --force-reinstall
 
     - name: Run unit test
+      shell: bash -l {0}
       run: |
-        conda init bash
-        source ~/.bashrc
         conda activate hierarchSIR
         pytest src/tests/test_lpp.py
